/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jakewharton.smsbarrage;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int app_about=0x7f050004;
        public static final int app_by=0x7f050003;
        public static final int app_name=0x7f050001;
        public static final int app_version=0x7f050002;
        public static final int icon=0x7f050000;
        public static final int label=0x7f05000d;
        public static final int message=0x7f050009;
        public static final int name=0x7f05000c;
        public static final int name_and_label=0x7f05000b;
        public static final int number=0x7f05000e;
        public static final int number_of_messages=0x7f050008;
        public static final int number_of_messages_count=0x7f050007;
        public static final int number_of_messages_text=0x7f050006;
        public static final int recipients_editor=0x7f050005;
        public static final int send=0x7f05000a;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
        public static final int recipient_filter_item=0x7f030002;
    }
    public static final class string {
        public static final int agree=0x7f04000d;
        public static final int app_about=0x7f040004;
        public static final int app_by=0x7f040003;
        public static final int app_name=0x7f040000;
        public static final int app_name_about=0x7f040001;
        public static final int app_version=0x7f040002;
        public static final int default_count=0x7f040008;
        public static final int default_delay=0x7f04000a;
        public static final int delay=0x7f040009;
        public static final int disagree=0x7f04000e;
        public static final int error=0x7f040012;
        public static final int error_title=0x7f040011;
        public static final int menu_about=0x7f040005;
        public static final int message_hint=0x7f040014;
        public static final int number_of_messages=0x7f040007;
        public static final int ok=0x7f040013;
        public static final int send=0x7f040015;
        public static final int sending=0x7f04000b;
        public static final int stop=0x7f04000c;
        public static final int to_hint=0x7f040006;
        public static final int warning=0x7f040010;
        public static final int warning_title=0x7f04000f;
    }
}
